### ISSUE TITLE
Disable global search when not available for navigation

### ISSUE THREAD

**Issue by sohaibafifi** [kirschbaum-development/nova-mail#38]
Is it possible to exclude `NovaSentMail`from the global search when the `nova_mail.show_resources.nova_sent_mail` config is `false`. 

And probably `NovaSentMailPolicy::view` too

**Comment by adammparker** [comment]
It looks like this can't be done via `searchable()` as underneath Nova only checks `$globallySearchable` as a property of the Resource (not a method). Fortunately it looks like `viewAny` on the policy will work though to hide from global search.

We might need to add a new config option similar to `show_resources` that determines if a resource should be globally searchable.

**Comment by adammparker** [comment]
@sohaibafifi I dug into this a bit more, the problem is when Nova returns the resources that are globally searchable it does it based only on the class property `$globallySearchable`. That would be fine on its own since we could potentially set that value dynamically based on config during resource construction, but the problem is it's a static property so you can't actually change it.

The only solution here that I can see is extending the resource in your application and then set that value to false in your extended resource.

Sorry about that!
